### ISSUE TITLE
Ant Monitor does not collect network traffic in Android 12

### ISSUE THREAD

**Issue by eruwan** [UCI-Networking-Group/OVRseen#1]
When turning on TSL interception AntMonitor app crash

**Comment by rtrimana** [comment]
@eruwan Thank you so much for using OVRseen. It looks like we will not update AntMonitor for Android 12. Please feel free to use other MiTM tools that can intercept network traffic as well, or you can also try to file an issue on https://github.com/UCI-Networking-Group/AntMonitor. However, the team that maintains AntMonitor seemed to say that they will not support AntMonitor for Android 12 and above.
