### ISSUE TITLE
Unable to automate with frida on some Quest Pro apps

### ISSUE THREAD

**Issue by sgsravya97** [UCI-Networking-Group/OVRseen#4]
Hi,

I'm trying OVRseen on Meta Quest Pro.

When I try below step for some apps, I don't see repackaged APK(the zipped file with underscore) getting generated like _com.some.application.apk which is not allowing me to proceed with further steps.
For few apps, I see repackaged APK getting generated. 

> OVRseen/network_traffic/traffic_collection/apk_processing $ ./frida_automate.sh APKs/obb/ password APKs/com.beatgames.beatsaber.demo.apk # This will generate the repackaged APK as _com.beatgames.beatsaber.demo.apk

Can you help me understand why this is happening? What kind of apps should I or shouldn't I try with OVRseen?

Appreciate your help! :)

**Comment by rtrimana** [comment]
Hi @sgs-97 , thanks so much for filing this issue. I believe our team has seen some issue like this in the past as well: not every app could be repackaged and that was back in 2021. I am guessing now Meta has applied more strict security measures on these VR apps.

One thing you could try, just as a baseline, is to try this first on the demo version of BeatSaber. I think you should still be able to repackage that one at the very least. Most of the free apps/games should also still be repackage-able with OVRseen. The paid ones usually have better security measures.

In general though, if you can see a .apk file with underscore in front of it then you can easily use ADB to install that one into your headset.

Hope this helps clarify things. Please let us know if you have further questions/concerns.

OVRseen Team

**Comment by sgsravya97** [comment]
Hi @rtrimana,

Thanks for your prompt response!
